version: '3'

networks:
  proxy_network:
    driver: bridge

services:

  mysql:
    image: mysql:8.0.36
    env_file: ./env/mysql.env
    volumes:
      - ./mysql-data-1:/var/lib/mysql
    networks:
      - proxy_network
    restart: unless-stopped
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    image: nicolasfrech/estudarte:1.1
    env_file: ./env/app.env
    networks:
      - proxy_network
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql-data-1: